# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
    - label: Pages
      link: /
      submenu:
          - label: Introduction
            link: /
          - label: Setting up a project
            link: /setting_up_a_project
          - label: Working + updating a project
            link: /working_updating_a_project
          - label: Deploying a project
            link: /deploying_a_project
          - label: Development Checklist
            link: /development_checklist
          - label: Fixing common issues
            link: /fixing_issues
    - label: The Bolt site
      link: http://bolt.cm
      class: last
